language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo apt-get update
install:
  - sudo apt-get install -qq ubuntu-sdk libc6:i386 xvfb
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.10.2-Linux-i386.tar.gz
  - tar -xzvf cmake-2.8.10.2-Linux-i386.tar.gz
before_script:
  - ./cmake-2.8.10.2-Linux-i386/bin/cmake .
script:
  - make VERBOSE=1
  - xvfb-run make test
