language: cpp
compiler:
  - gcc
env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: "VgJE/OzDvDdxK+arumGwyx+rCh7eSoo9B4/ZVZ+jn0uI4wSteKCvJcPeyV86LXj8U/r6Jk5VTzhyKnv2Ac6RpgO3OL8M+rSFHdKlVLq/oNKwBWBcFzTryVnGjYDmHCbGsp99VqtG21go7vYSKaBIi5xyLyRxzSXU6X1lyyKtYtw="
addons:
  coverity_scan:
    project:
      name: "vimofthevine/UnderBudget"
      description: "Advanced personal budget analysis"
    notification_email: kyle@vimofthevine.com
    build_command_prepend: "./cmake-2.8.10.2-Linux-i386/bin/cmake ."
    build_command: "make"
    branch_pattern: coverity_scan
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa # for Qt5
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # for gcc 4.8
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq ubuntu-sdk libc6:i386 xvfb
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  # make sure compilation uses gcc 4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.10.2-Linux-i386.tar.gz
  - tar -xzvf cmake-2.8.10.2-Linux-i386.tar.gz
  - git clone --branch development --depth 1 https://github.com/saschazelzer/CppMicroServices.git
  - (cd CppMicroServices && cmake -DCMAKE_CXX_FLAGS="-std=c++11 -DUS_NO_INFO_OUTPUT" -DUS_ENABLE_AUTOLOADING_SUPPORT=OFF -DUS_ENABLE_THREADING_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=../us && make install)
before_script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then ./cmake-2.8.10.2-Linux-i386/bin/cmake -DCppMicroServices_DIR=./us/share/CppMicroServices/cmake . ; fi
script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then make VERBOSE=1 ; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then xvfb-run make test; fi
