language: c++
dist: trusty
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/gtest-1.8.0

env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: "VgJE/OzDvDdxK+arumGwyx+rCh7eSoo9B4/ZVZ+jn0uI4wSteKCvJcPeyV86LXj8U/r6Jk5VTzhyKnv2Ac6RpgO3OL8M+rSFHdKlVLq/oNKwBWBcFzTryVnGjYDmHCbGsp99VqtG21go7vYSKaBIi5xyLyRxzSXU6X1lyyKtYtw="

addons:
  apt:
    packages:
      - g++-6
      - libsqlite3-dev
      - qtbase5-dev
      - qtscript5-dev
      - libqt5xmlpatterns5-dev
      - xvfb
    sources:
      - ubuntu-sdk-team
      - ubuntu-toolchain-r-test
  coverity_scan:
    project:
      name: "vimofthevine/UnderBudget"
      description: "Personal finance and budget manager"
    notification_email: kyle@vimofthevine.com
    build_command_prepend: "export GTEST_ROOT=${TRAVIS_BUILD_DIR}/deps/gtest-1.8.0; export CXX=${CXX_COMPILER}; export CC=${C_COMPILER}; cmake ."
    build_command: "make -j 4"
    branch_pattern: coverity_scan

matrix:
  include:
    - os: linux
      env: CXX_COMPILER=g++-6 C_COMPILER=gcc-6
      compiler: gcc

install:
  - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
  - if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake -DCMAKE_INSTALL_PREFIX="${DEPS_DIR}/gtest-1.8.0" -DBUILD_SHARED_LIBS=ON .
  - make
  - make install
  - cd "${TRAVIS_BUILD_DIR}"
before_script:
  - export GTEST_ROOT=${TRAVIS_BUILD_DIR}/deps/gtest-1.8.0
  - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi
  - if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then cmake . ; fi
script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then make VERBOSE=1 -j 4; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then xvfb-run make CTEST_OUTPUT_ON_FAILURE=1 test; fi
