language: c++
dist: trusty

env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: "VgJE/OzDvDdxK+arumGwyx+rCh7eSoo9B4/ZVZ+jn0uI4wSteKCvJcPeyV86LXj8U/r6Jk5VTzhyKnv2Ac6RpgO3OL8M+rSFHdKlVLq/oNKwBWBcFzTryVnGjYDmHCbGsp99VqtG21go7vYSKaBIi5xyLyRxzSXU6X1lyyKtYtw="
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - GTEST_ROOT="${DEPS_DIR}/gtest-1.8.0"


matrix:
  include:
    - os: linux
      addons:
        compiler: gcc
        apt:
          sources:
            - ubuntu-sdk-team
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt58-trusty'
          packages:
            - g++-4.9
            - libsqlite3-dev
            - mesa-common-dev
            - qt58base
            - qt58charts-no-lgpl
            - qt58script
            - qt58xmlpatterns
            - xvfb
        coverity_scan:
          project:
            name: "vimofthevine/UnderBudget"
            description: "Personal finance and budget manager"
          notification_email: kyle@vimofthevine.com
          build_command_prepend: "export GTEST_ROOT=${TRAVIS_BUILD_DIR}/deps/gtest-1.8.0; cmake ."
          build_command: "cmake --build ."
          branch_pattern: coverity_scan
      env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
install:
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake -DCMAKE_INSTALL_PREFIX="${GTEST_ROOT}" -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake --build . --target install
  - cd "${TRAVIS_BUILD_DIR}"
before_script:
  - source $(find /opt -name "qt*-env.sh")
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then cmake . ; fi
script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then cmake --build . -- VERBOSE=1; fi
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 ]]; then xvfb-run ctest --output-on-failure; fi
