/*
 * Copyright 2013 Kyle Treubig
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef GNUCASH_TESTDATA_HPP
#define GNUCASH_TESTDATA_HPP

namespace ub {

namespace GnuCashTest {

//------------------------------------------------------------------------------
const QString Header =
	"<?xml version=\"1.0\" encoding=\"utf-8\" ?>"
	"<gnc-v2"
	"     xmlns:gnc=\"http://www.gnucash.org/XML/gnc\""
	"     xmlns:act=\"http://www.gnucash.org/XML/act\""
	"     xmlns:book=\"http://www.gnucash.org/XML/book\""
	"     xmlns:cd=\"http://www.gnucash.org/XML/cd\""
	"     xmlns:cmdty=\"http://www.gnucash.org/XML/cmdty\""
	"     xmlns:price=\"http://www.gnucash.org/XML/price\""
	"     xmlns:slot=\"http://www.gnucash.org/XML/slot\""
	"     xmlns:split=\"http://www.gnucash.org/XML/split\""
	"     xmlns:sx=\"http://www.gnucash.org/XML/sx\""
	"     xmlns:trn=\"http://www.gnucash.org/XML/trn\""
	"     xmlns:ts=\"http://www.gnucash.org/XML/ts\""
	"     xmlns:fs=\"http://www.gnucash.org/XML/fs\""
	"     xmlns:bgt=\"http://www.gnucash.org/XML/bgt\""
	"     xmlns:recurrence=\"http://www.gnucash.org/XML/recurrence\""
	"     xmlns:lot=\"http://www.gnucash.org/XML/lot\""
	"     xmlns:addr=\"http://www.gnucash.org/XML/addr\""
	"     xmlns:owner=\"http://www.gnucash.org/XML/owner\""
	"     xmlns:billterm=\"http://www.gnucash.org/XML/billterm\""
	"     xmlns:bt-days=\"http://www.gnucash.org/XML/bt-days\""
	"     xmlns:bt-prox=\"http://www.gnucash.org/XML/bt-prox\""
	"     xmlns:cust=\"http://www.gnucash.org/XML/cust\""
	"     xmlns:employee=\"http://www.gnucash.org/XML/employee\""
	"     xmlns:entry=\"http://www.gnucash.org/XML/entry\""
	"     xmlns:invoice=\"http://www.gnucash.org/XML/invoice\""
	"     xmlns:job=\"http://www.gnucash.org/XML/job\""
	"     xmlns:order=\"http://www.gnucash.org/XML/order\""
	"     xmlns:taxtable=\"http://www.gnucash.org/XML/taxtable\""
	"     xmlns:tte=\"http://www.gnucash.org/XML/tte\""
	"     xmlns:vendor=\"http://www.gnucash.org/XML/vendor\">"
	"<gnc:count-data cd:type=\"book\">1</gnc:count-data>"
	"<gnc:book version=\"2.0.0\">"
	"<book:id type=\"guid\">acfba4b01f9152d8201fd68ead5d41ef</book:id>"
	"<gnc:count-data cd:type=\"commodity\">1</gnc:count-data>"
	"<gnc:count-data cd:type=\"account\">110</gnc:count-data>"
	"<gnc:count-data cd:type=\"transaction\">2192</gnc:count-data>"
	"<gnc:commodity version=\"2.0.0\">"
	"  <cmdty:space>ISO4217</cmdty:space>"
	"  <cmdty:id>USD</cmdty:id>"
	"  <cmdty:get_quotes/>"
	"  <cmdty:quote_source>currency</cmdty:quote_source>"
	"  <cmdty:quote_tz/>"
	"</gnc:commodity>"
	"<gnc:commodity version=\"2.0.0\">"
	"  <cmdty:space>template</cmdty:space>"
	"  <cmdty:id>template</cmdty:id>"
	"  <cmdty:name>template</cmdty:name>"
	"  <cmdty:xcode>template</cmdty:xcode>"
	"  <cmdty:fraction>1</cmdty:fraction>"
	"</gnc:commodity>";

//------------------------------------------------------------------------------
const QString Footer =
	"</gnc:book>"
	"</gnc-v2>";

//------------------------------------------------------------------------------
const QString RootAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Root Account</act:name>"
	"  <act:id type=\"guid\">0719754ce69a13860400bdbb10208c99</act:id>"
	"  <act:type>ROOT</act:type>"
	"</gnc:account>";
const QString IncomeAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Income</act:name>"
	"  <act:id type=\"guid\">e5ac6df44bca821c1bc995648882d121</act:id>"
	"  <act:type>INCOME</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Income</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString SalaryAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Salary</act:name>"
	"  <act:id type=\"guid\">758c06364fadd3291575f7f882497317</act:id>"
	"  <act:type>INCOME</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Salary</act:description>"
	"  <act:parent type=\"guid\">e5ac6df44bca821c1bc995648882d121</act:parent>"
	"</gnc:account>";
const QString GiftsReceivedAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Gifts Received</act:name>"
	"  <act:id type=\"guid\">e515bc7178b9b727d040ebc63feb324b</act:id>"
	"  <act:type>INCOME</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Gifts Received</act:description>"
	"  <act:parent type=\"guid\">e5ac6df44bca821c1bc995648882d121</act:parent>"
	"</gnc:account>";
const QString ExpensesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Expenses</act:name>"
	"  <act:id type=\"guid\">eceaa02c949d069221002337cc64e06b</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Expenses</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString TaxesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Taxes</act:name>"
	"  <act:id type=\"guid\">23cd74d70b6fcc6b47b74520c077c1ce</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Taxes</act:description>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString FederalAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Federal</act:name>"
	"  <act:id type=\"guid\">b08e7fe2c1700aac7f22b8b3e2839fa5</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Federal</act:description>"
	"  <act:parent type=\"guid\">23cd74d70b6fcc6b47b74520c077c1ce</act:parent>"
	"</gnc:account>";
const QString SocialSecurityAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Social Security</act:name>"
	"  <act:id type=\"guid\">e8db7dd76fb4c9949612604489984eb0</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Social Security</act:description>"
	"  <act:parent type=\"guid\">23cd74d70b6fcc6b47b74520c077c1ce</act:parent>"
	"</gnc:account>";
const QString StateAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>State/Province</act:name>"
	"  <act:id type=\"guid\">c8ddf1572d16b626c0158f3e270556ed</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>State/Province</act:description>"
	"  <act:parent type=\"guid\">23cd74d70b6fcc6b47b74520c077c1ce</act:parent>"
	"</gnc:account>";
const QString InsuranceAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Insurance</act:name>"
	"  <act:id type=\"guid\">7e108ac17870a6fbd3ae9dd4f709f4f6</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Insurance</act:description>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString HomeInsuranceAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Home Insurance</act:name>"
	"  <act:id type=\"guid\">3b0d357852cc7f0bcb9c134d8bc4d464</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Home Insurance</act:description>"
	"  <act:parent type=\"guid\">7e108ac17870a6fbd3ae9dd4f709f4f6</act:parent>"
	"</gnc:account>";
const QString AutoInsuranceAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Auto Insurance</act:name>"
	"  <act:id type=\"guid\">8c827e4ae9857b56f92a740c65b30d38</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Auto Insurance</act:description>"
	"  <act:parent type=\"guid\">7e108ac17870a6fbd3ae9dd4f709f4f6</act:parent>"
	"</gnc:account>";
const QString EntertainmentAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Entertainment</act:name>"
	"  <act:id type=\"guid\">577fdaf3e1556222679bdc8cb4f8c588</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Entertainment</act:description>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString MusicMoviesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Music/Movies</act:name>"
	"  <act:id type=\"guid\">16c808d1e3049cfc62c146b5b8c7b234</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Music/Movies</act:description>"
	"  <act:parent type=\"guid\">577fdaf3e1556222679bdc8cb4f8c588</act:parent>"
	"</gnc:account>";
const QString RecreationAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Recreation</act:name>"
	"  <act:id type=\"guid\">1ea0b84947dc777419b10bb6eb577fa1</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Recreation</act:description>"
	"  <act:parent type=\"guid\">577fdaf3e1556222679bdc8cb4f8c588</act:parent>"
	"</gnc:account>";
const QString DiningAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Dining</act:name>"
	"  <act:id type=\"guid\">20dbb46b09ed99dd1bc234ed3e858bd9</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Dining</act:description>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString GroceriesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Groceries</act:name>"
	"  <act:id type=\"guid\">156e4459be0795966c7adda412e246db</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Groceries</act:description>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString HousewaresAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Housewares</act:name>"
	"  <act:id type=\"guid\">d71d9d997b7ebbfa2ea598b94959a086</act:id>"
	"  <act:type>EXPENSE</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>color</slot:key>"
	"      <slot:value type=\"string\">Not Set</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">eceaa02c949d069221002337cc64e06b</act:parent>"
	"</gnc:account>";
const QString LiabilitiesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Liabilities</act:name>"
	"  <act:id type=\"guid\">0d1ca57e12fccfafa336e23a7f239f92</act:id>"
	"  <act:type>LIABILITY</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Liabilities</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString CreditCardAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Credit Card</act:name>"
	"  <act:id type=\"guid\">a65c38cc7416d30a0c00af945ec61646</act:id>"
	"  <act:type>CREDIT</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Capital One Credit Card</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>color</slot:key>"
	"      <slot:value type=\"string\">Not Set</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0d1ca57e12fccfafa336e23a7f239f92</act:parent>"
	"</gnc:account>";
const QString MerchantCreditCardAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Merchant Credit Card</act:name>"
	"  <act:id type=\"guid\">aedfab2c34a0e72f06667a1c5193d7ac</act:id>"
	"  <act:type>CREDIT</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Zales Diamond Card</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>color</slot:key>"
	"      <slot:value type=\"string\">Not Set</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0d1ca57e12fccfafa336e23a7f239f92</act:parent>"
	"</gnc:account>";
const QString LoansAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Loans</act:name>"
	"  <act:id type=\"guid\">d9932e48d7ddc3feefe267fc100d1368</act:id>"
	"  <act:type>LIABILITY</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Loans</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString MortgageLoanAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Mortgage Loan</act:name>"
	"  <act:id type=\"guid\">85073b07c799535c35bba1f234b45fdb</act:id>"
	"  <act:type>LIABILITY</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Mortgage Loan</act:description>"
	"  <act:parent type=\"guid\">d9932e48d7ddc3feefe267fc100d1368</act:parent>"
	"</gnc:account>";
const QString AssetsAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Assets</act:name>"
	"  <act:id type=\"guid\">d27e61b52bd1cf89160c449d39ba317c</act:id>"
	"  <act:type>ASSET</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Assets</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString CurrentAssetsAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Current Assets</act:name>"
	"  <act:id type=\"guid\">8cd23f8f38d78784066650b63981ae07</act:id>"
	"  <act:type>ASSET</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Current Assets</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">d27e61b52bd1cf89160c449d39ba317c</act:parent>"
	"</gnc:account>";
const QString BankCheckingAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Bank Checking Account</act:name>"
	"  <act:id type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</act:id>"
	"  <act:type>BANK</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Checking Account</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>reconcile-info</slot:key>"
	"      <slot:value type=\"frame\">"
	"        <slot>"
	"          <slot:key>include-children</slot:key>"
	"          <slot:value type=\"integer\">0</slot:value>"
	"        </slot>"
	"        <slot>"
	"          <slot:key>last-date</slot:key>"
	"          <slot:value type=\"integer\">1382587199</slot:value>"
	"        </slot>"
	"        <slot>"
	"          <slot:key>last-interval</slot:key>"
	"          <slot:value type=\"frame\">"
	"            <slot>"
	"              <slot:key>days</slot:key>"
	"              <slot:value type=\"integer\">0</slot:value>"
	"            </slot>"
	"            <slot>"
	"              <slot:key>months</slot:key>"
	"              <slot:value type=\"integer\">1</slot:value>"
	"            </slot>"
	"          </slot:value>"
	"        </slot>"
	"      </slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">8cd23f8f38d78784066650b63981ae07</act:parent>"
	"</gnc:account>";
const QString CashInWalletAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Cash in Wallet</act:name>"
	"  <act:id type=\"guid\">1b6e99b9f405e7defb41968b1542f837</act:id>"
	"  <act:type>CASH</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Cash in Wallet</act:description>"
	"  <act:parent type=\"guid\">8cd23f8f38d78784066650b63981ae07</act:parent>"
	"</gnc:account>";
const QString EquityAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Equity</act:name>"
	"  <act:id type=\"guid\">76d64ce5636e5776a2a5e1d1571cd1c4</act:id>"
	"  <act:type>EQUITY</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Equity</act:description>"
	"  <act:slots>"
	"    <slot>"
	"      <slot:key>placeholder</slot:key>"
	"      <slot:value type=\"string\">true</slot:value>"
	"    </slot>"
	"  </act:slots>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString OpeningBalancesAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Opening Balances</act:name>"
	"  <act:id type=\"guid\">a5a9df8655199aaed54c6c758f62b495</act:id>"
	"  <act:type>EQUITY</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:description>Opening Balances</act:description>"
	"  <act:parent type=\"guid\">76d64ce5636e5776a2a5e1d1571cd1c4</act:parent>"
	"</gnc:account>";
const QString OrphanAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Orphan-USD</act:name>"
	"  <act:id type=\"guid\">e76ea696d56d2705b044275ca6090a51</act:id>"
	"  <act:type>BANK</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";
const QString ImbalanceAccount =
	"<gnc:account version=\"2.0.0\">"
	"  <act:name>Imbalance-USD</act:name>"
	"  <act:id type=\"guid\">e733440e81a63619744188be428cbf95</act:id>"
	"  <act:type>BANK</act:type>"
	"  <act:commodity>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </act:commodity>"
	"  <act:commodity-scu>100</act:commodity-scu>"
	"  <act:parent type=\"guid\">0719754ce69a13860400bdbb10208c99</act:parent>"
	"</gnc:account>";

//------------------------------------------------------------------------------
const QString FullAccountsList = RootAccount
	+ IncomeAccount + SalaryAccount + GiftsReceivedAccount
	+ ExpensesAccount
	+ TaxesAccount + FederalAccount + SocialSecurityAccount + StateAccount
	+ InsuranceAccount + HomeInsuranceAccount + AutoInsuranceAccount
	+ EntertainmentAccount + MusicMoviesAccount + RecreationAccount
	+ DiningAccount + GroceriesAccount + HousewaresAccount
	+ LiabilitiesAccount + CreditCardAccount + MerchantCreditCardAccount
	+ LoansAccount + MortgageLoanAccount
	+ AssetsAccount + CurrentAssetsAccount + BankCheckingAccount + CashInWalletAccount
	+ EquityAccount + OpeningBalancesAccount + OrphanAccount + ImbalanceAccount;

//------------------------------------------------------------------------------
const QString MissingParentAccountsList = RootAccount
	+ IncomeAccount + SalaryAccount + GiftsReceivedAccount
	+ ExpensesAccount
	+ TaxesAccount + FederalAccount + SocialSecurityAccount + StateAccount
	+ InsuranceAccount + HomeInsuranceAccount + AutoInsuranceAccount
	+ MusicMoviesAccount + RecreationAccount // missing entertainment parent
	+ DiningAccount + GroceriesAccount + HousewaresAccount
	+ LiabilitiesAccount + CreditCardAccount + MerchantCreditCardAccount
	+ LoansAccount + MortgageLoanAccount
	+ AssetsAccount + CurrentAssetsAccount + BankCheckingAccount + CashInWalletAccount
	+ EquityAccount + OpeningBalancesAccount + OrphanAccount + ImbalanceAccount;

//------------------------------------------------------------------------------
const QString PaydayTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">ddced263c632aa5876d4ec13105a864b</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-08 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-09 20:17:48 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Payday</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>date-posted</slot:key>"
	"      <slot:value type=\"gdate\">"
	"        <gdate>2013-11-06</gdate>"
	"      </slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">967cc6d830129017a6a2dffcb7141d01</split:id>"
	"      <split:memo>Earned paycheck</split:memo>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-23 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>79955/100</split:value>"
	"      <split:quantity>79955/100</split:quantity>"
	"      <split:account type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">8e996fed2dc122584f465e0d08128cf0</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>15821/100</split:value>"
	"      <split:quantity>15821/100</split:quantity>"
	"      <split:account type=\"guid\">b08e7fe2c1700aac7f22b8b3e2839fa5</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">d134c04e6e0980e74819ad1e5a9974a3</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>9421/100</split:value>"
	"      <split:quantity>9421/100</split:quantity>"
	"      <split:account type=\"guid\">e8db7dd76fb4c9949612604489984eb0</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">03e40f29b25227f735a66d2bf60e8ef9</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>4326/100</split:value>"
	"      <split:quantity>4326/100</split:quantity>"
	"      <split:account type=\"guid\">c8ddf1572d16b626c0158f3e270556ed</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">1065292f8e0ac14f8b5984d4d10b4bf1</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>-109523/100</split:value>"
	"      <split:quantity>-109523/100</split:quantity>"
	"      <split:account type=\"guid\">758c06364fadd3291575f7f882497317</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString BirthdayGiftTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">92b97018a2fbd401ab13708c7fee96e2</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-17 00:00:00 -0400</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-19 16:04:21 -0400</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Birthday gift</trn:description>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">f2e392853e770e5499ab555ebd47dee3</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>5000/100</split:value>"
	"      <split:quantity>5000/100</split:quantity>"
	"      <split:account type=\"guid\">1b6e99b9f405e7defb41968b1542f837</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">7e08d38e9eebe82f1c906d5aef529e2c</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>-5000/100</split:value>"
	"      <split:quantity>-5000/100</split:quantity>"
	"      <split:account type=\"guid\">e515bc7178b9b727d040ebc63feb324b</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString MultiExpenseTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">e82caa62df41b5ed2098eee833e5c5e6</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-01 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-08 11:27:15 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Merchant</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>notes</slot:key>"
	"      <slot:value type=\"string\"></slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">7def4297f6f429f28b6e65675e987e75</split:id>"
	"      <split:memo>Groceries</split:memo>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>2800/100</split:value>"
	"      <split:quantity>2800/100</split:quantity>"
	"      <split:account type=\"guid\">156e4459be0795966c7adda412e246db</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">ba0cbbb1b925f487bc92d20f4a2e1f7a</split:id>"
	"      <split:memo>Housewares</split:memo>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>4889/100</split:value>"
	"      <split:quantity>4889/100</split:quantity>"
	"      <split:account type=\"guid\">d71d9d997b7ebbfa2ea598b94959a086</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">9a6fbb826661bf6b5637ee2d156a1404</split:id>"
	"      <split:memo>DVD</split:memo>" "      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>1000/100</split:value>"
	"      <split:quantity>1000/100</split:quantity>"
	"      <split:account type=\"guid\">16c808d1e3049cfc62c146b5b8c7b234</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">9d10e63a7c0b30ee977bedf4f8217cd3</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-24 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-8689/100</split:value>"
	"      <split:quantity>-8689/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString CashWithdrawalTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">411c0149412a1cff0d5c27c8d4368b5e</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-12 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-13 20:07:06 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Cash from ATM</trn:description>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">8b20e01c045b4e9a547dac884cdc846d</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>8000/100</split:value>"
	"      <split:quantity>8000/100</split:quantity>"
	"      <split:account type=\"guid\">1b6e99b9f405e7defb41968b1542f837</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">a12bbfc392c0c809829a772137a173f0</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-23 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-8000/100</split:value>"
	"      <split:quantity>-8000/100</split:quantity>"
	"      <split:account type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString CreditCardPaymentTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">c326c0f107515623b8fe30d29b99034c</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-24 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-24 21:49:01 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>CC Payment</trn:description>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">4d80b612a64f151cbf03a5319ff4bd33</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-12-03 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>25382/100</split:value>"
	"      <split:quantity>25382/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">470798daec72d990fe4d8cc820e39a35</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-23 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-25382/100</split:value>"
	"      <split:quantity>-25382/100</split:quantity>"
	"      <split:account type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString RefundTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">c85ed46dc40a151d42540a47ac06fd82</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-16 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-21 14:51:14 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Merchant</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>notes</slot:key>"
	"      <slot:value type=\"string\"></slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">fb4abcc94c64a8c783576ef90ed76d6c</split:id>"
	"      <split:memo>Return lamp</split:memo>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>6543/100</split:value>"
	"      <split:quantity>6543/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">1173c96fa61a4ad2c3f241c6fbc77c0d</split:id>"
	"      <split:reconciled-state>c</split:reconciled-state>"
	"      <split:value>-6543/100</split:value>"
	"      <split:quantity>-6543/100</split:quantity>"
	"      <split:account type=\"guid\">d71d9d997b7ebbfa2ea598b94959a086</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString ZeroImbalanceTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">4dc8c48c24f277894dc1f9d2d4b8d17b</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-20 00:00:00 -0400</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-22 17:21:33 -0400</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Merchant</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>date-posted</slot:key>"
	"      <slot:value type=\"gdate\">"
	"        <gdate>2013-11-20</gdate>"
	"      </slot:value>"
	"    </slot>"
	"    <slot>"
	"      <slot:key>notes</slot:key>"
	"      <slot:value type=\"string\"></slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">57a403943a558cee6c11d849d80927ac</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>3209/100</split:value>"
	"      <split:quantity>3209/100</split:quantity>"
	"      <split:account type=\"guid\">d71d9d997b7ebbfa2ea598b94959a086</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">82a260443b3eb8bad4c01e5c8d10a8fd</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>650/100</split:value>"
	"      <split:quantity>650/100</split:quantity>"
	"      <split:account type=\"guid\">156e4459be0795966c7adda412e246db</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">ca45e095f32551983053df91acb15871</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>0/100</split:value>"
	"      <split:quantity>0/100</split:quantity>"
	"      <split:account type=\"guid\">e733440e81a63619744188be428cbf95</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">ee20af2ffc1df253317be3f402953bf4</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-05-03 23:59:59 -0400</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-3859/100</split:value>"
	"      <split:quantity>-3859/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString LastTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">e7e9c6f60ba0f6109872ba0d091e5698</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-30 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-30 21:11:22 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Ice Skating</trn:description>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">6a1281c326dd05cabd179e8a78a8f58b</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>1783/100</split:value>"
	"      <split:quantity>1783/100</split:quantity>"
	"      <split:account type=\"guid\">1ea0b84947dc777419b10bb6eb577fa1</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">e5c2c4bb76a5d0474e613b94361d4a4c</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>-1783/100</split:value>"
	"      <split:quantity>-1783/100</split:quantity>"
	"      <split:account type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString BeforeTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">96739c6767aa4ba4c84b0bf6b88cd206</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-10-31 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-02 16:20:24 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Grocer</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>date-posted</slot:key>"
	"      <slot:value type=\"gdate\">"
	"        <gdate>2013-10-31</gdate>"
	"      </slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">e1373c4723b7431ff839c8a779bade52</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>5672/100</split:value>"
	"      <split:quantity>5672/100</split:quantity>"
	"      <split:account type=\"guid\">156e4459be0795966c7adda412e246db</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">d37cdd6fc84b8954d8dda156c575ede3</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-03 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-5672/100</split:value>"
	"      <split:quantity>-5672/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString AfterTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">5d4466bb7d31de2fd7a0d761d1dcc3b1</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-12-01 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-12-01 21:11:22 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Restaurant</trn:description>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">6a1281c326dd05cabd179e8a78a8f58b</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>640/100</split:value>"
	"      <split:quantity>640/100</split:quantity>"
	"      <split:account type=\"guid\">20dbb46b09ed99dd1bc234ed3e858bd9</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">e5c2c4bb76a5d0474e613b94361d4a4c</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-12-23 23:59:59 -0400</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-640/100</split:value>"
	"      <split:quantity>-640/100</split:quantity>"
	"      <split:account type=\"guid\">348db0cafbfde5f85ec65a657a0dd26e</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString AllTransactions = BeforeTrn + PaydayTrn + BirthdayGiftTrn
	+ MultiExpenseTrn + CashWithdrawalTrn + CreditCardPaymentTrn + RefundTrn
	+ ZeroImbalanceTrn + LastTrn + AfterTrn;

//------------------------------------------------------------------------------
const QString InvalidAccountTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">96739c6767aa4ba4c84b0bf6b88cd206</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-06 00:00:00 -0500</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-20 16:20:24 -0500</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Grocer</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>date-posted</slot:key>"
	"      <slot:value type=\"gdate\">"
	"        <gdate>2013-11-06</gdate>"
	"      </slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">e1373c4723b7431ff839c8a779bade52</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>5672/100</split:value>"
	"      <split:quantity>5672/100</split:quantity>"
	"      <split:account type=\"guid\">8a338b114d992d0936529f0a49c04ed3</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">d37cdd6fc84b8954d8dda156c575ede3</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-11-03 23:59:59 -0500</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-5672/100</split:value>"
	"      <split:quantity>-5672/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

//------------------------------------------------------------------------------
const QString NonZeroImbalanceTrn =
	"<gnc:transaction version=\"2.0.0\">"
	"  <trn:id type=\"guid\">ceac9511d7f7c761c677fd9f623cc46c</trn:id>"
	"  <trn:currency>"
	"    <cmdty:space>ISO4217</cmdty:space>"
	"    <cmdty:id>USD</cmdty:id>"
	"  </trn:currency>"
	"  <trn:date-posted>"
	"    <ts:date>2013-11-20 00:00:00 -0400</ts:date>"
	"  </trn:date-posted>"
	"  <trn:date-entered>"
	"    <ts:date>2013-11-22 17:21:33 -0400</ts:date>"
	"  </trn:date-entered>"
	"  <trn:description>Merchant</trn:description>"
	"  <trn:slots>"
	"    <slot>"
	"      <slot:key>date-posted</slot:key>"
	"      <slot:value type=\"gdate\">"
	"        <gdate>2013-11-20</gdate>"
	"      </slot:value>"
	"    </slot>"
	"    <slot>"
	"      <slot:key>notes</slot:key>"
	"      <slot:value type=\"string\"></slot:value>"
	"    </slot>"
	"  </trn:slots>"
	"  <trn:splits>"
	"    <trn:split>"
	"      <split:id type=\"guid\">57a403943a558cee6c11d849d80927ac</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>3200/100</split:value>"
	"      <split:quantity>3200/100</split:quantity>"
	"      <split:account type=\"guid\">d71d9d997b7ebbfa2ea598b94959a086</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">82a260443b3eb8bad4c01e5c8d10a8fd</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>650/100</split:value>"
	"      <split:quantity>650/100</split:quantity>"
	"      <split:account type=\"guid\">156e4459be0795966c7adda412e246db</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">ca45e095f32551983053df91acb15871</split:id>"
	"      <split:reconciled-state>n</split:reconciled-state>"
	"      <split:value>-9/100</split:value>"
	"      <split:quantity>-9/100</split:quantity>"
	"      <split:account type=\"guid\">e733440e81a63619744188be428cbf95</split:account>"
	"    </trn:split>"
	"    <trn:split>"
	"      <split:id type=\"guid\">ee20af2ffc1df253317be3f402953bf4</split:id>"
	"      <split:reconciled-state>y</split:reconciled-state>"
	"      <split:reconcile-date>"
	"        <ts:date>2013-05-03 23:59:59 -0400</ts:date>"
	"      </split:reconcile-date>"
	"      <split:value>-3859/100</split:value>"
	"      <split:quantity>-3859/100</split:quantity>"
	"      <split:account type=\"guid\">a65c38cc7416d30a0c00af945ec61646</split:account>"
	"    </trn:split>"
	"  </trn:splits>"
	"</gnc:transaction>";

}

}

#endif //GNUCASH_TESTDATA_HPP
